services:
  # MongoDB Database
  mongodb:
    image: mongo:8.0.12
    container_name: pagamento-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: test_fadesp
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - pagamento-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: pagamento-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - pagamento-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: pagamento-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: pagamento-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - pagamento-network
    
  backend:
    build:
      context: ./backend/pagamento
      dockerfile: Dockerfile
    container_name: pagamento-backend
    restart: unless-stopped
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin123@mongodb:27017/test_fadesp?authSource=admin
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - pagamento-network

  frontend:
    build:
      context: ./frontend/pagamento
      dockerfile: Dockerfile
    container_name: pagamento-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - pagamento-network

networks:
  pagamento-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  kafka_data:
    driver: local
  zookeeper_data:    
    driver: local
  zookeeper_logs:   
    driver: local